### ISSUE TITLE
Icon Stuck In Status Bar.

### ISSUE THREAD

**Issue by iAdam1n** [hbang/TypeStatus#45]
Icon will stick in status bar until respring or reboot.

**Comment by iAdam1n** [comment]
This is fixed with TypeStatus 1.3.

**Comment by iAdam1n** [comment]
Still happens when using "Test Typing" and going back to the home screen without opening another app.

**Comment by iAdam1n** [comment]
This is back in 1.3.1.

**Comment by kirb** [comment]
Should be fixed by fef3034
