### ISSUE TITLE
iPad Settings Crash.

### ISSUE THREAD

**Issue by ReddestDream** [hbang/TypeStatus#64]
Tapping the "box with arrow" crashes the Settings app on iPads. The logs are provided below.

Thanks! ^_^

Crash: https://ghostbin.com/paste/re5rn

Syslog: https://ghostbin.com/paste/3bubb

**Comment by iAdam1n** [comment]
This is actually a bug in Cephei. Moved to https://github.com/hbang/libcephei/issues/6.
